# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Minecraft Stuff
# check these on https://fabricmc.net/develop
minecraft_version=1.20.6
loader_version=0.16.5
quilt_mappings=6
# parchment_version=2024.04.14

# Mod Thingies
mod_version = 1.20.6+3.1-8-fix
maven_group = ml.pluto7073
archives_base_name = PlutosCoffeeMod-Fabric

# Things I might be dependent on
# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api
fabric_version=0.100.8+1.20.6
cloth_version=14.0.139
modmenu_version=10.0.0
rei_version=15.0.775
architectury_version=12.1.4
pdapi_version=2.0.4-1-fix
